services:
  gateway:
    ports: !reset []
    networks:
      default: {}
      skinnai_default:
        aliases:
          - africa-gateway

networks:
  skinnai_default:
    external: true
    name: skinnai_default
